# Project information
site_name: '咖啡屋 | 轨迹系列 - Cafe'
site_description: '轨迹游戏剧情和脚本'
site_author: '轨迹系列 - Cafe'
site_url: 'https://book.trails-game.com'

# Copyright
copyright: "<p>ICP备案: <a href='https://beian.miit.gov.cn' target='_blank' rel='noopener'>沪ICP备2021002641号-1</a></p><p>沪公网安备: <a href='http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=31010402008841' target='_blank' rel='noopener'>31010402008841号</a></p>"

# Repository
repo_name: 'GitHub'
repo_url: https://github.com/trails-game/trails-script-mkdocs" target="_blank

theme:
  name: material
  custom_dir: mkdocs-material/material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: 暗色模式
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: 浅色模式

  # 404 page
  static_templates:
    - 404.html

  # Default values, taken from mkdocs_theme.yml
  language: zh
  font: false
  icon:
    repo: fontawesome/brands/git-alt
  favicon: images/webicons/favicon-32x32.png
  logo: images/webicons/apple-touch-icon.webp

  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
# plugins
plugins:
  - git-revision-date-localized:
      type: datetime
      enable_creation_date: true
  - search:
      jieba_dict: dict.txt
      lang:
        - ja
        - en
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/trails-game
extra_css:
  - stylesheets/glightbox.min.css
  - stylesheets/extra.css
extra_javascript:
  - https://code.jquery.com/jquery-3.6.0.min.js
  - javascripts/glightbox.min.js
  - javascripts/extra.js
# Page tree
nav:
  - 'Cafe主站': https://trails-game.com" target="_blank
  # Summary
  - '黎之轨迹Ⅱ':
    - '黎之轨迹Ⅱ - 剧情简介': 'kuro2/summary.md'
    - '序幕 「绯红咆哮」': 'kuro2/chapter-0.md'
    - '幕前 「童话庭园」': 'kuro2/chapter-pre.md'
    - '第Ⅰ部side A  「北方港都随想曲」': 'kuro2/chapter-1a.md'
    - '第Ⅰ部side B 「代理地下万事屋」': 'kuro2/chapter-1b.md'
    - '第Ⅱ部side A 「再访煌都～黑月撩乱～」': 'kuro2/chapter-2a.md'
    - '第Ⅱ部side B 「潜入亚拉密斯～并不那么悠闲的日子～」': 'kuro2/chapter-2b.md'
    - '断章 「涅梅丝岛～另一个节日～」': 'kuro2/chapter-mid.md'
    - '第Ⅲ部 「普世欢腾」': 'kuro2/chapter-3.md'
    - '尾声 「流转的终点」': 'kuro2/chapter-4.md'
    - 'EXTRA 「扭曲童话者～然后……」': 'kuro2/chapter-extra.md'
    - '连结事件': 'kuro2/bond-events.md'
    - '电影文本&全角色赏析': 'kuro2/movies.md'
    - '调查报告&有声故事': 'kuro2/extrastories.md'
  - '黎之轨迹':
    - '黎之轨迹 - 剧情简介': 'kuro/summary.md'
    - '序章 「旧市街的地下万事屋」': 'kuro/chapter-0.md'
    - '第一章 「纯真之焰～启程～」': 'kuro/chapter-1.md'
    - '第二章 「宿星～煌都的麒麟儿」': 'kuro/chapter-2.md'
    - '第三章 「萨尔巴德狂想曲」': 'kuro/chapter-3.md'
    - '第四章 「灾厄协定」': 'kuro/chapter-4.md'
    - '间章 「龙来温泉乡奇谭」': 'kuro/chapter-4-5.md'
    - '第五章 「白夜的嘉年华」': 'kuro/chapter-5.md'
    - '最终章 「为了总有一天终将归来的你」': 'kuro/chapter-6.md'
    - '连结事件': 'kuro/bond-events.md'
    - '电影文本&全角色赏析': 'kuro/movies.md'
  - '创之轨迹':
    - '创之轨迹 - 剧情简介': 'hajimari/summary.md'
    - '序章 「克洛斯贝尔解放作战」': 'hajimari/chapter-0.md'
    - '第一章': 'hajimari/chapter-1.md'
    - '第二章': 'hajimari/chapter-2.md'
    - '第三章': 'hajimari/chapter-3.md'
    - '第四章': 'hajimari/chapter-4.md'
    - '终章 「终焉，以及创始」': 'hajimari/chapter-5.md'
    - '额外章节 「前往梦幻的彼端」': 'hajimari/dlc.md'
    - '追忆石盘':
      - '章节': 'hajimari/episode.md'
      - '退路、岔路、前方的路': 'hajimari/episodes/ep1.md'
      - '再出发～支援课的一天': 'hajimari/episodes/ep2.md'
      - '女子学院事件簿～美嘉与美丽的剑士～': 'hajimari/episodes/ep3.md'
      - '令人怀念的家乡': 'hajimari/episodes/ep4.md'
      - '白兔与沉睡的傀儡': 'hajimari/episodes/ep5.md'
      - '光辉中的全新一步': 'hajimari/episodes/ep6.md'
      - '重逢～少女的忧郁～': 'hajimari/episodes/ep7.md'
      - '我所选择的路': 'hajimari/episodes/ep8.md'
      - '两人的正义': 'hajimari/episodes/ep9.md'
      - '堕落的皇子': 'hajimari/episodes/ep10.md'
      - '新·导力装甲开发计划 前篇': 'hajimari/episodes/ep11.md'
      - '新·导力装甲开发计划 后篇': 'hajimari/episodes/ep12.md'
      - '魔女们的追忆': 'hajimari/episodes/ep13.md'
      - '同窗的标杆': 'hajimari/episodes/ep14.md'
      - '究极的野味': 'hajimari/episodes/ep15.md'
      - '幸运之石与不幸之船': 'hajimari/episodes/ep16.md'
      - '无尽之剑': 'hajimari/episodes/ep17.md'
      - '猜猜我是谁': 'hajimari/episodes/ep18.md'
      - '布莱特家的假日': 'hajimari/episodes/ex1.md'
      - '踏出的一步': 'hajimari/episodes/ex2.md'
      - '回忆的眼神无比火热': 'hajimari/episodes/ex3.md'
      - '第Ⅱ分校研修祭': 'hajimari/episodes/ex4.md'
    - '创始的彼方':
      - '前言': 'hajimari/extra.md'
      - '另一个温泉乡': 'hajimari/extras/extra1.md'
      - '某位少女的校园生活': 'hajimari/extras/extra2.md'
      - '于是少女将握著手中的剑继续前进': 'hajimari/extras/extra3.md'
    - '游戏方石': 'hajimari/games.md'
    - '试炼之门': 'hajimari/battles.md'
    - '附录：特殊战斗胜利对话': 'hajimari/victory.md'
  - '闪之轨迹Ⅳ':
    - '闪之轨迹Ⅳ - 剧情简介': 'sen4/summary.md'
  - '闪之轨迹Ⅲ':
    - '闪之轨迹Ⅲ - 剧情简介': 'sen3/summary.md'
    - '序章 ｢春日再临｣': 'sen3/chapter-0.md'
  - '闪之轨迹Ⅱ':
    - '闪之轨迹Ⅱ - 剧情简介': 'sen2/summary.md'
    - '序章 「归乡～失意的尽头～」': 'sen2/chapter-0.md'
    - '第Ⅰ部 「灰色战记」': 'sen2/chapter-1.md'
    - '幕间 「白银巨船」': 'sen2/chapter-1-5.md'
    - '第Ⅱ部 「红翼～苏醒的狮子们」': 'sen2/chapter-2.md'
    - '外传 ｢边境小镇阿尔斯塔｣': 'sen2/memoir.md'
    - '终章 ｢只管一路向前｣': 'sen2/chapter-3.md'
    - '外传 「占领下的克洛斯贝尔」': 'sen2/chapter-4.md'
    - '后日谭 「冬日的尾声」': 'sen2/chapter-5.md'
    - '全羁绊事件': 'sen2/bond-events.md'
  - '闪之轨迹Ⅰ':
    - '闪之轨迹Ⅰ - 剧情简介': 'sen1/summary.md'
    - '序章 ｢托尔兹军官学院｣': 'sen1/chapter-0.md'
    - '第一章 ｢新学期～首次实习～｣': 'sen1/chapter-1.md'
    - '第二章 ｢美丽翡翠之都｣': 'sen1/chapter-2.md'
    - '第三章 ｢横跨铁路～苍穹的大地～｣': 'sen1/chapter-3.md'
    - '第四章 ｢绯之帝都 ～仲夏祭～｣': 'sen1/chapter-4.md'
    - '第五章 ｢开始行动的意志｣': 'sen1/chapter-5.md'
    - '第六章 ｢黑与银～钢都动乱～｣': 'sen1/chapter-6.md'
    - '幕间 ｢返乡～迷惘的尽头～｣': 'sen1/intermission.md'
    - '终章 ｢军官学院祭，然后──｣': 'sen1/chapter-7.md'
    - '全羁绊事件': 'sen1/bond-events.md'
  - '碧之轨迹':
    - '碧之轨迹 - 剧情简介': 'aoi/summary.md'
    - '序章 ｢D之残影｣': 'aoi/prologue.md'
    - '第一章 ｢预兆～崭新的日子｣': 'aoi/chapter-1.md'
    - '第二章 ｢西塞姆里亚通商会议｣': 'aoi/chapter-2.md'
    - '间章 ｢短暂的休息｣': 'aoi/intermission.md'
    - '第三章 ｢胎动～众兽的狂欢节｣': 'aoi/chapter-3.md'
    - '第四章 ｢命运未卜的克洛斯贝尔｣': 'aoi/chapter-4.md'
    - '断章 ｢跨越虚幻的乐土｣': 'aoi/intermission2.md'
  - '零之轨迹':
    - '零之轨迹 - 剧情简介': 'zero/summary.md'
    - '序章 ｢特别任务支援科｣': 'zero/prologue.md'
    - '第一章 ｢神狼们的午后｣': 'zero/chapter-1.md'
    - '第二章 ｢金之太阳、银之月｣': 'zero/chapter-2.md'
    - '第三章 ｢克洛斯贝尔创立纪念庆典｣': 'zero/chapter-3.md'
    - '间章 ｢琪雅｣': 'zero/intermission.md'
    - '第四章 ｢悄然袭来的睿智｣': 'zero/chapter-4.md'
    - '终章 ｢克洛斯贝尔最漫长的一日｣': 'zero/finale.md'
  - '空之轨迹3RD':
    - '空之轨迹3RD - 剧情简介': 'sora-3rd/summary.md'
    - '第零话 ｢星杯骑士｣': 'sora-3rd/chapter-0.md'
    - '第一话 ｢影之国｣': 'sora-3rd/chapter-1.md'
    - '第二话 ｢异界化王都｣': 'sora-3rd/chapter-2.md'
    - '第三话 ｢金之道，银之道｣': 'sora-3rd/chapter-3.md'
    - '第四话 ｢昏暗圣痕｣': 'sora-3rd/chapter-4.md'
    - '第五话 ｢光与影的迷宫｣': 'sora-3rd/chapter-5.md'
    - '第六话 ｢守护者的试炼｣': 'sora-3rd/chapter-6.md'
    - '第七话 ｢邃远的炙炎｣': 'sora-3rd/chapter-7.md'
    - '最终话 ｢时光的终焉，艰辛的彼岸｣': 'sora-3rd/chapter-8.md'
    - '星之门':
      - '章节': 'sora-3rd/star.md'
      - '｢尤莉亚大人的假日｣': 'sora-3rd/doors/star-1.md'
      - '｢盐之桩｣': 'sora-3rd/doors/star-2.md'
      - '｢庆祝会之夜｣': 'sora-3rd/doors/star-3.md'
      - '｢旅途的终点｣': 'sora-3rd/doors/star-4.md'
      - '｢剑之道｣': 'sora-3rd/doors/star-5.md'
      - '｢重剑流特训法｣': 'sora-3rd/doors/star-6.md'
      - '｢爱普斯泰恩财团｣': 'sora-3rd/doors/star-7.md'
      - '｢回归帝都｣': 'sora-3rd/doors/star-8.md'
      - '｢操之过急的关怀｣': 'sora-3rd/doors/star-9.md'
      - '｢戈尔地雅斯级实验计划书｣': 'sora-3rd/doors/star-10.md'
      - '｢『怪盗B』调查报告｣': 'sora-3rd/doors/star-11.md'
      - '｢调查委托，敬悉｣': 'sora-3rd/doors/star-12.md'
      - '｢帝国支部连续袭击事件｣': 'sora-3rd/doors/star-13.md'
      - '｢幻焰计划｣': 'sora-3rd/doors/star-14.md'
      - '｢乐园的少女｣': 'sora-3rd/doors/star-15.md'
      - '｢科洛丝的毕业典礼｣（废案）': 'sora-3rd/doors/star-16-annulled.md'
      - '｢酒的诱惑｣（废案）': 'sora-3rd/doors/star-17-annulled.md'
      - '｢百日战役的新星｣（废案）': 'sora-3rd/doors/star-18-annulled.md'
      - '｢圣痕的背叛｣（废案）': 'sora-3rd/doors/star-19-annulled.md'
      - '｢执行者的真实｣（废案）': 'sora-3rd/doors/star-20-annulled.md'
    - '月之门':
      - '章节': 'sora-3rd/moon.md'
      - '｢导力装甲开发计划/前篇｣': 'sora-3rd/doors/moon-1-1.md'
      - '｢导力装甲开发计划/后篇｣': 'sora-3rd/doors/moon-1-2.md'
      - '｢委托人｣': 'sora-3rd/doors/moon-2.md'
      - '｢飘落的羽翼｣': 'sora-3rd/doors/moon-3.md'
      - '｢启程的清晨｣': 'sora-3rd/doors/moon-4.md'
      - '｢幸福之石｣': 'sora-3rd/doors/moon-5.md'
    - '太阳之门':
      - '章节': 'sora-3rd/sun.md'
      - '｢山猫卡普亚的特快专递｣': 'sora-3rd/doors/sun-1.md'
      - '｢爆钓传说艾丝蒂尔｣': 'sora-3rd/doors/sun-2.md'
      - '｢THE CASINO ～赌博师杰克～｣': 'sora-3rd/doors/sun-4.md'
  - '空之轨迹SC':
    - '空之轨迹SC - 剧情简介': 'sora-sc/summary.md'
    - '序章 ｢少女的决意｣': 'sora-sc/chapter-0.md'
    - '第一章 ｢潜行的白影｣': 'sora-sc/chapter-1.md'
    - '第二章 ｢狂暴的大地｣': 'sora-sc/chapter-2.md'
    - '第三章 ｢纷乱的茶会｣': 'sora-sc/chapter-3.md'
    - '第四章 ｢雾魔的标矢｣': 'sora-sc/chapter-4.md'
    - '第五章 ｢守护的信念｣': 'sora-sc/chapter-5.md'
    - '第六章 ｢羁绊的所在｣': 'sora-sc/chapter-6.md'
    - '第七章 ｢四轮之塔｣': 'sora-sc/chapter-7.md'
    - '第八章 ｢迷乱的大地｣': 'sora-sc/chapter-8.md'
    - '终章 ｢空之轨迹｣': 'sora-sc/chapter-9.md'
  - '空之轨迹FC':
    - '空之轨迹FC - 剧情简介': 'sora-fc/summary.md'
    - '序章 ｢父亲，启程｣': 'sora-fc/chapter-0.md'
    - '第一章 ｢消失的定期船｣': 'sora-fc/chapter-1.md'
    - '第二章 ｢白花恋诗｣': 'sora-fc/chapter-2.md'
    - '第三章 ｢黑色导力器｣': 'sora-fc/chapter-3.md'
    - '终章 ｢王都缭乱｣': 'sora-fc/chapter-4.md'
