name: ci
on:
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Build mkdocs-material with custom setting
        run: |
          cd mkdocs-material
          npm i
          sed -i 's/24px/48px/g' src/templates/assets/stylesheets/main/components/_header.scss
          sed -i 's/16px/32px/g' src/templates/assets/stylesheets/main/components/_footer.scss
          npm run build
          cd ..

      - name: Install python dependencies
        run: |
          python3 -m pip install mkdocs-material
          pip3 install -r requirements.txt

      - name: Build mkdocs
        run: mkdocs build