name: ci
on:
  push:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build mkdocs-material with custom setting
        run: |
          cd mkdocs-material
          npm i
          sed -i 's/24px/48px/g' src/assets/stylesheets/main/layout/_header.scss
          sed -i 's/16px/32px/g' src/assets/stylesheets/main/layout/_footer.scss
          npm run build
          cd ..

      - name: Install python dependencies
        run: |
          pip3 install -e mkdocs-material
          pip3 install -r requirements.txt

      - name: Build mkdocs and deploy
        run: mkdocs gh-deploy --force

      - name: Compress search index and copy .htaccess and Google verification file
        run: |
          brotli -q 9 site/search/search_index.json
          cp .htaccess googlee6574b95bbae1639.html site/

      - name: Generate robots.txt
        run: |
          cat > site/robots.txt <<EOF
          User-agent: *
          Allow: /

          Sitemap: https://book.trails-game.com/sitemap.xml
          EOF

      - name: Upload mkdocs artifacts
        uses: actions/upload-artifact@v2
        with:
          name: mkdocs-artifacts
          path: site

  deploy-oss:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: yizhoumo/setup-ossutil@v1
        with:
          ossutil-version: '1.7.9' # Optional, default to '1.7.0'
          endpoint: oss-cn-hangzhou.aliyuncs.com
          access-key-id: ${{secrets.ACCESS_ID}}
          access-key-secret: ${{secrets.ACCESS_KEY_SECRET}}

      - name: Download mkdocs artifacts
        uses: actions/download-artifact@v2
        with:
          path: site
          name: mkdocs-artifacts

      - name: Sync artifacts to OSS
        run: ossutil sync site/ ${{secrets.BUCKET}} -u --delete -f
