name: ci
on:
  push:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build mkdocs-material with custom setting
        run: |
          cp overrides/footer.html mkdocs-material/src/partials/
          cd mkdocs-material
          npm i
          sed -i 's/24px/48px/g' src/assets/stylesheets/main/layout/_header.scss
          sed -i 's/16px/32px/g' src/assets/stylesheets/main/layout/_footer.scss
          npm run build
          cd ..

      - name: Install python dependencies
        run: |
          pip3 install -r requirements.txt

      - name: Build mkdocs and deploy
        run: mkdocs gh-deploy --force

      - name: Compress search index and copy .htaccess
        run: |
          brotli -q 9 site/search/search_index.json
          cp .htaccess site/

      - name: Generate robots.txt 
        run: |
          cat > site/robots.txt <<EOF
          User-agent: *
          Allow: /
          
          Sitemap: https://book.trails-game.com/sitemap.xml
          EOF

Sitemap: http://scodoc.org/sitemap.xml
EOF

      - name: Upload mkdocs artifacts
        uses: actions/upload-artifact@v2
        with:
          name: mkdocs-artifacts
          path: site

  deploy-us:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Setup SSH for target host
      uses: kielabokkie/ssh-key-and-known-hosts-action@v1.1.0
      with:
        # Private key required to access the host
        ssh-private-key: ${{ secrets.FISH_SSH }}
        # Hostname or IP to add to the known hosts file
        ssh-host: ${{ secrets.US_HOST }}

    - name: Download mkdocs artifacts
      uses: actions/download-artifact@v2
      with:
        path: site
        name: mkdocs-artifacts

    - name: Upload to server
      env:
        HOST: ${{ secrets.US_HOST }}
      run: rsync -avz site/ ubuntu@${HOST}:/var/www/book/ --delete-after

  deploy-kr:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Setup SSH for target host
      uses: kielabokkie/ssh-key-and-known-hosts-action@v1.1.0
      with:
        # Private key required to access the host
        ssh-private-key: ${{ secrets.FISH_SSH }}
        # Hostname or IP to add to the known hosts file
        ssh-host: ${{ secrets.KR_HOST }}

    - name: Download mkdocs artifacts
      uses: actions/download-artifact@v2
      with:
        path: site
        name: mkdocs-artifacts

    - name: Upload to server
      env:
        HOST: ${{ secrets.KR_HOST }}
      run: rsync -avz site/ ubuntu@${HOST}:/var/www/book/ --delete-after
